apiVersion: apps/v1
kind: Deployment
metadata:
  name: xml-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xml
  template:
    metadata:
      labels:
        app: xml
    spec:
      containers:
        - name: xml
          image: phobopt/xml          
          env:            
            - name: MONGO_URI
              value: mongodb://xml-mongo-srv:27017/xml
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: xml-srv
spec:
  selector:
    app: xml
  ports:
    - name: xml
      protocol: TCP
      port: 3000
      targetPort: 3000    